    
FONT_SIZE=30
WIDTH_SIZE = 24
AVATAR_SIZE=75

# Margin between avatar and message bubble
AVATAR_MARGIN=10

BUBBLE_X_START= AVATAR_SIZE + AVATAR_MARGIN
BUBBLE_RADIUS=35
BUBBLE_PADDING=25

TEXT_X_START= BUBBLE_X_START + BUBBLE_PADDING